<a href="https://colab.research.google.com/github/AdamStamm/data_science/blob/main/Notebooks/Acessando_dados_do_SUS_com_PySUS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Instalação da biblioteca

In [1]:
!pip install PySUS

Requirement already satisfied: PySUS in /usr/local/lib/python3.6/dist-packages (0.4.8)
Requirement already satisfied: fastparquet in /usr/local/lib/python3.6/dist-packages (from PySUS) (0.4.1)
Requirement already satisfied: dbfread in /usr/local/lib/python3.6/dist-packages (from PySUS) (2.0.7)
Requirement already satisfied: geocoder in /usr/local/lib/python3.6/dist-packages (from PySUS) (1.38.1)
Requirement already satisfied: cffi>=1.0.0 in /usr/local/lib/python3.6/dist-packages (from PySUS) (1.14.3)
Requirement already satisfied: pyarrow in /usr/local/lib/python3.6/dist-packages (from PySUS) (0.14.1)
Requirement already satisfied: requests in /usr/local/lib/python3.6/dist-packages (from PySUS) (2.23.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.6/dist-packages (from PySUS) (1.1.4)
Requirement already satisfied: numba>=0.28 in /usr/local/lib/python3.6/dist-packages (from fastparquet->PySUS) (0.48.0)
Requirement already satisfied: six in /usr/local/lib/python3.6/dist-packages (from fastparquet->PySUS) (1.15.0)
Requirement already satisfied: thrift>=0.11.0 in /usr/local/lib/python3.6/dist-packages (from fastparquet->PySUS) (0.13.0)
Requirement already satisfied: numpy>=1.11 in /usr/local/lib/python3.6/dist-packages (from fastparquet->PySUS) (1.18.5)
Requirement already satisfied: packaging in /usr/local/lib/python3.6/dist-packages (from fastparquet->PySUS) (20.4)
Requirement already satisfied: future in /usr/local/lib/python3.6/dist-packages (from geocoder->PySUS) (0.16.0)
Requirement already satisfied: click in /usr/local/lib/python3.6/dist-packages (from geocoder->PySUS) (7.1.2)
Requirement already satisfied: ratelim in /usr/local/lib/python3.6/dist-packages (from geocoder->PySUS) (0.1.6)
Requirement already satisfied: pycparser in /usr/local/lib/python3.6/dist-packages (from cffi>=1.0.0->PySUS) (2.20)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests->PySUS) (2020.11.8)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests->PySUS) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests->PySUS) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests->PySUS) (2.10)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.6/dist-packages (from pandas->PySUS) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.6/dist-packages (from pandas->PySUS) (2018.9)
Requirement already satisfied: llvmlite<0.32.0,>=0.31.0dev0 in /usr/local/lib/python3.6/dist-packages (from numba>=0.28->fastparquet->PySUS) (0.31.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.6/dist-packages (from numba>=0.28->fastparquet->PySUS) (50.3.2)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.6/dist-packages (from packaging->fastparquet->PySUS) (2.4.7)
Requirement already satisfied: decorator in /usr/local/lib/python3.6/dist-packages (from ratelim->geocoder->PySUS) (4.4.2)

#Import de biblioteca

In [2]:
from pysus.online_data import SIH

#Acessando dados

In [3]:
dados = SIH.download('PR', 2020, '2')
dados.head()

    UF_ZI ANO_CMPT MES_CMPT ESPEC  ... TPDISEC6 TPDISEC7 TPDISEC8 TPDISEC9
0  410000     2020       02    01  ...        0        0        0        0
1  410000     2020       02    01  ...        0        0        0        0
2  410000     2020       02    01  ...        0        0        0        0
3  410000     2020       02    01  ...        0        0        0        0
4  410000     2020       02    01  ...        0        0        0        0

[5 rows x 113 columns]

É necessário informar no método download o estado, o ano (em inteiro) e o mês (em string) conforme acima.

In [5]:
dados.head()

    UF_ZI ANO_CMPT MES_CMPT ESPEC  ... TPDISEC6 TPDISEC7 TPDISEC8 TPDISEC9
0  410000     2020       02    01  ...        0        0        0        0
1  410000     2020       02    01  ...        0        0        0        0
2  410000     2020       02    01  ...        0        0        0        0
3  410000     2020       02    01  ...        0        0        0        0
4  410000     2020       02    01  ...        0        0        0        0

[5 rows x 113 columns]

In [8]:
#Definindo uma função para download de bases genéricas.
def baixando_dados_sih(estado, ano, mes):
  dados = SIH.download(estado, ano, mes)
  return dados

In [9]:
teste = baixando_dados_sih('PR', 2020, '2')

Percebi que existe um fator dificultante em utilizar a função pois o código fonte do pysus realizar um comando .upper() em uma lista de strings (no caso a de estados) e dessa forma o python retorna um erro. Vou estudar outras formas de automatizar essa extração posteriormente.

In [10]:
fev_2020 = baixando_dados_sih('PR', 2020, '2')
mar_2020 = baixando_dados_sih('PR', 2020, '3')
abr_2020 = baixando_dados_sih('PR', 2020, '4')

In [11]:
print(f'o número de linhas de fev_2020 eh: {fev_2020.shape[0]}')
print(f'o número de linhas de mar_2020 eh: {mar_2020.shape[0]}')
print(f'o número de linhas de abr_2020 eh: {abr_2020.shape[0]}')

o número de linhas de fev_2020 eh: 75184
o número de linhas de mar_2020 eh: 68857
o número de linhas de abr_2020 eh: 56146